### ISSUE TITLE
magic

### ISSUE THREAD

**Issue by chesner** [loonpwn/blockfolio-php#1]
Hi @loonpwn,

Thanks a lot for creating this library public. I've done a quick check, and it appears their secret is hardcoded for this version, so always `edtopjhgn2345piuty89whqejfiobh89-2q453` for build 1.1.10.225.

Best regards,
Dan!

**Comment by harlan-zw** [comment]
Hi @chesner 

Thanks for looking into the code. Just to quickly check, this it for version 1.2 right? 

This was a known issue in version 1/1.1 where I was unsure what the magic was for since it wasn't being used to validate anything. Version 1.2 it needed to be fixed for the library to continue working, which should be the case

**Comment by harlan-zw** [comment]
Actually @chesner I spotted the issue you were talking about, this is now fixed in version 1.3. Thanks for the feedback
